spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:13306/batch?useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password:

  batch:
    job:
      names: ${job.name:NONE} # spring.batch.job.names 값이 없을 경우 모든 job이 실행되므로 job.name이 없는 경우 NONE으로 할당하여 모든 batch job을 실행하지 않도록 함

  jpa:
    show-sql: true

# mysql 사용 시 table을 직접 생성해줘야 한다. schema는 아래 경로에 작성되어있다.
## spring batch DB table Setting schema
## classpath:/org/springframework/batch/core/schema-mysql.sql
